hackernews:
  name: Hacker News
  category: Tech
  default: false
theblaze:
  name: The Blaze
  category: Opinion
  default: true
nypost:
  name: New York Post
  category: Opinion
  default: true
huffpost_blogs:
  name: Huffington Post Blogs
  category: Opinion
  default: true
thinkprogress:
  name: ThinkProgress
  category: Opinion
  default: true
tmz:
  name: TMZ
  category: Entertainment
  default: false
giantbomb:
  name: Giant Bomb
  category: Games
  default: true
kotaku:
  name: Kotaku
  category: Games
  default: true
buzzfeed:
  name: BuzzFeed
  category: Trash
  default: true
upworthy:
  name: Upworthy
  category: Trash
  default: true
gawker:
  name: Gawker
  category: Trash
  default: true
defamer:
  name: Defamer
  category: Entertainment
  default: true
jezebel:
  name: Jezebel
  category: Entertainment
  default: true
io9:
  name: io9
  category: Entertainment
  default: true
tested:
  name: Tested
  category: Tech
  default: true
r_politics:
  name: r/politics
  category: Reddit
  default: false
r_funny:
  name: r/funny
  category: Reddit
  default: false
cnn_blog:
  name: CNN News Blog
  category: News
  default: false
guardian_blogs:
  name: Guardian Blogs
  category: News
  default: true
nature_blog:
  name: Nature Blog
  category: Science
  default: true
npr_two_way:
  name: NPR Two Way
  category: News
  default: false
nytimes_lede:
  name: New York Times Lede
  category: News
  default: true